#!/bin/bash

# Update package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx to serve "Hello World!"
echo 'Hello World' | sudo tee /var/www/html/index.html

# Start Nginx
sudo service nginx start