#!/usr/bin/env bash
# Configures an Ubuntu serverwith specific IP addresses
# to `localhost` and `facebook.com` hostname

cp /etc/hosts ~/hosts.new
sed -i s/^127.*localhost$/127.0.0\ localhost ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.n> /etc/hosts
