#!/usr/bin/env bash
# This script runs the 'whoami' command under the specified user.

# check if a user was provided as an argument
if [ $# -eq 0 ]; then
	echo "Usage: $0 username"
	exit 1
fi

# run 'whoami' as the specified user
sudo -u $1 whoami
