#!/usr/bin/env bash
# Run Nginx as Nginx User

chmod 644 /etc/nginx/nginx.conf
pkill apache2

if ! id -u nginx >/dev/null 2>&1; then
	echo "Creating nginx user.."
	sudo useradd -s /bin/false nginx
fi

sudo service nginx stop
sudo sed -i '/^user /c\user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80/listen 8080;/g' /etc/nginx/sites-available/default

sudo -u nginx service nginx start
